windowrule {
    name = Wallpaper
    match:class = wallpaper
      float = on
      no_focus = on
      pin = on
}


windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}


# # IntelliJ IDEA Menus
# windowrulev2 = float, title:^(win.*)$

# Workspace
workspace = s[true], gapsin:50, gapsout:150
workspace = special:spotify, on-created-empty:GLFW_IM_MODULE=ibus kitty --class Spotify ncmpcpp &, gapsin:50, gapsout:150
workspace = special:tablet, on-created-empty:otd-gui, gapsin:50, gapsout:150
workspace = special:pavu, on-created-empty:pavucontrol, gapsin:50, gapsout:150
workspace = special:files, on-created-empty:nautilus, gapsin:50, gapsout:150

