source = $HOME/.config/hypr/all/binds.conf
source = $HOME/.config/hypr/all/layouts.conf
source = $HOME/.config/hypr/all/devices.conf
source = $HOME/.config/hypr/all/windowrules.conf
source = $HOME/.config/hypr/all/hyprwinwrap.conf
source = $HOME/.config/hypr/all/monitors.conf

debug {
    # suppress_errors = true
}


###############
### VISUALS ###
###############

source = $HOME/.config/hypr/dark/visuals.conf
# source = $HOME/.config/hypr/light/visuals.conf


exec-once = mpd-mpris
exec-once = fcitx5
exec-once = udiskie

###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$menu = rofi --show drun

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc { 
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    vrr = true # Variable Refresh Rate
}


####################
### KEYBINDINGSS ###
####################


# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

