# Path
export PATH="$PATH:/home/harrek/Scripts"
export PATH="$PATH:/home/harrek/Applications"
export PATH="$PATH:/home/harrek/.local/bin"
export EDITOR="/usr/bin/nvim"
export XDG_DATA_DIRS="~/.local/share/sounds:${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}"

export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS=@im=fcitx5


# Aliases
alias yay="yay --noconfirm"
# alias cd="z"

alias vim='nvim'
alias v='nvim'
alias vi='nvim'
alias f='"$(fzf)"'  
alias vf='nvim "$(fzf)"'

alias neofetch='clear && neofetch'
alias surf='GDK_BACKEND=x11 /usr/local/bin/surf'
alias icat='kitten icat'
alias theme='wal --theme'

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias feh='feh --zoom fill'
alias ls='ls --color=auto'
alias feh='feh --scale-down'
alias xo='xdg-open'

alias v='nvim'
alias f=fzf
alias gpt=chatgpt
alias thorium=thorium-browser
alias f.="find . | fzf"
alias xof='nohup xdg-open "$(fzf)"'
alias vf='nvim "$(fzf)"'
alias vf.='nvim "$(find . | fzf)"'
alias vcg='nvim .config/nvim/'
alias zf='zathura "$(fzf)" & disown && exit'
alias vcf='nvim "$(dirname "$(fzf)")"'
alias neofetch='clear && neofetch'

alias cf='cd "`find . -type d -print 2>/dev/null | fzf`"'
alias cf='cd "$(dirname "$(fzf)")"'
alias wk="firefox --fullscreen --new-window https://www.wanikani.com/subjects/review & disown"
alias zath="nohup zathura & disown"

alias mkc=". mkc "

alias :q="exit"
alias :wqa="exit"
alias q="exit"
alias :w="exit"


# Misc aliases
alias weather="clear && curl wttr.in/Bathurst"
alias jc="clear && jisho-cli -i"

alias pd=pushd
alias ppd=popd
alias dirs='dirs -v'




# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' file-sort name
zstyle ':completion:*' format 'Completion: %d'
zstyle ':completion:*' ignore-parents pwd
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]} r:|[._-]=** r:|=**' 'l:|=* r:|=*'
zstyle ':completion:*' max-errors 3
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' prompt '%e errors.'
zstyle ':completion:*' squeeze-slashes true
zstyle :compinstall filename '/home/harrek/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd extendedglob
bindkey -v
# End of lines configured by zsh-newuser-install

# Plugins
PLUGIN_FOLDER=/usr/share/zsh/plugins
source $PLUGIN_FOLDER/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
source $PLUGIN_FOLDER/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh

autoload -U compinit; compinit

zstyle ':completion:*' menu select

# Starship
eval "$(starship init zsh)"

# Atuin
eval "$(atuin init zsh --disable-up-arrow)"

# Thefuck Alias
eval $(thefuck --alias)

# Zoxide
eval "$(zoxide init zsh)"

[ -f "/home/harrek/.ghcup/env" ] && source "/home/harrek/.ghcup/env" # ghcup-env
